### ISSUE TITLE
Domoticz: Devices Data strange

### ISSUE THREAD

**Issue by kruu51** [stas-demydiuk/domoticz-plugins-manager#19]
Installed the plugins manager, installed plugins from it. But whn I go in Settings-Devices, then in a row of Pythonplugins in Data field is all this:

`
{"type": "response", "requestId": 2, "isError": false, "payload": {"AAPIPModule": {"key": "AAPIPModule", "author": "febalci", "description": "Crow Runner Alarm", "name": "DomoticzCrowAlarm", "source": "https://github.com/febalci/DomoticzCrowAlarm/tree/master", "is_installed": false, "is_update_available": false}, "BatteryLevel": {"key": "BatteryLevel", "author": "999LV", "description": "Battery monitoring for Z-Wave nodes", "name": "BatteryLevel", "source": "https://github.com/999LV/BatteryLevel/tree/master", "is_installed": false, "is_update_available": false}, "Buienradar": {"key": "Buienradar", "author": "ffes", "description": "Buienradar.nl (Weather lookup)", "name": "domoticz-buienradar", "source": "https://github.com/ffes/domoticz-buienradar/tree/master", "is_installed": false, "is_update_available": false}, "ChromecastPlugin": {"key": "ChromecastPlugin", "author": "Tsjippy", "description": "Chromecast plugin for Domoticz", "name": "ChromecastPlugin", "source": "https://github.com/Tsjippy/ChromecastPlugin/tree/master", "is_installed": false, "is_update_available": false}, "Denon4306": {"key": "Denon4306", "author": "dnpwwo", "description": "Denon/Marantz Amplifier", "name": "Domoticz-Denon-Plugin", "source": "https://github.com/dnpwwo/Domoticz-Denon-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "DysonPureLink": {"key": "DysonPureLink", "author": "JanJaapKo", "description": "Domoticz plugin to integrate the Dyson PureLink devices", "name": "Dyson Pure Link", "source": "https://github.com/JanJaapKo/DysonPureLink/tree/master", "is_installed": false, "is_update_available": false}, "GC-100": {"key": "GC-100", "author": "dnpwwo", "description": "Global Cache 100", "name": "Domoticz-GlobalCache-Plugin", "source": "https://github.com/dnpwwo/Domoticz-GlobalCache-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "GoodWeAPI": {"key": "GoodWeAPI", "author": "JanJaapKo", "description": "Provides information about your GoodWe solar inverter too Domoticz", "name": "GoodWE Solar inverter via SEMS API", "source": "https://github.com/JanJaapKo/domoticz-GoodWeSEMS/tree/master", "is_installed": false, "is_update_available": false}, "Hisense-AEH-W4A1": {"key": "Hisense-AEH-W4A1", "author": "x-th-unicorn", "description": "Domoticz Python plugin for Hisense AC (AEH-W4A1)", "name": "domoticz-aeh-w4a1", "source": "https://github.com/x-th-unicorn/domoticz-aeh-w4a1/tree/master", "is_installed": false, "is_update_available": false}, "HivePlug": {"key": "HivePlug", "author": "imcfarla2003", "description": "Hive Plugin", "name": "domoticz-hive", "source": "https://github.com/imcfarla2003/domoticz-hive/tree/master", "is_installed": false, "is_update_available": false}, "Homewizard": {"key": "Homewizard", "author": "rvdvoorde", "description": "Homewizard", "name": "domoticz-homewizard", "source": "https://github.com/rvdvoorde/domoticz-homewizard/tree/master", "is_installed": false, "is_update_available": false}, "IKEA-Tradfri": {"key": "IKEA-Tradfri", "author": "moroen", "description": "IKEA Tradfri", "name": "IKEA-Tradfri-plugin", "source": "https://github.com/moroen/IKEA-Tradfri-plugin/tree/master", "is_installed": false, "is_update_available": false}, "Kodi": {"key": "Kodi", "author": "dnpwwo", "description": "Kodi Media Player Plugin", "name": "Kodi Players", "source": "https://github.com/dnpwwo/Domoticz-Kodi-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "Life360": {"key": "Life360", "author": "febalci", "description": "Life 360 Presence", "name": "DomoticzLife360", "source": "https://github.com/febalci/DomoticzLife360/tree/master", "is_installed": false, "is_update_available": false}, "Linky": {"key": "Linky", "author": "guillaumezin", "description": "Linky", "name": "DomoticzLinky", "source": "https://github.com/guillaumezin/DomoticzLinky/tree/master", "is_installed": false, "is_update_available": false}, "MQTTDiscovery": {"key": "MQTTDiscovery", "author": "emontnemery", "description": "MQTT discovery", "name": "domoticz_mqtt_discovery", "source": "https://github.com/emontnemery/domoticz_mqtt_discovery/tree/development", "is_installed": false, "is_update_available": false}, "MeteoAlarmEU": {"key": "MeteoAlarmEU", "author": "ycahome", "description": "Meteo Alarm EU RSS Reader", "name": "MeteoAlarmEU", "source": "https://github.com/ycahome/MeteoAlarmEU/tree/master", "is_installed": false, "is_update_available": false}, "Mi_Flower_mate": {"key": "Mi_Flower_mate", "author": "flatsiedatsie", "description": "Xiaomi Mi Flower Mate", "name": "Xiaomi Mi Flower Mate", "source": "https://github.com/flatsiedatsie/Mi_Flower_mate_plugin/tree/master", "is_installed": false, "is_update_available": false}, "MilightESP8266": {"key": "MilightESP8266", "author": "mrin", "description": "Support for ESP8266 Milight hub", "name": "ESP8266 Milight Hub", "source": "https://github.com/etsach/espmilighthub-domoticz/tree/master", "is_installed": false, "is_update_available": false}, "MoonPhases": {"key": "MoonPhases", "author": "ycahome", "description": "Moon Phases", "name": "MoonPhases", "source": "https://github.com/ycahome/MoonPhases/tree/master", "is_installed": false, "is_update_available": false}, "NUT_UPS": {"key": "NUT_UPS", "author": "999LV", "description": "UPS Monitor python plugin for Domoticz", "name": "UPS Monitor", "source": "https://github.com/999LV/NUT_UPS/tree/master", "is_installed": false, "is_update_available": false}, "Onkyo": {"key": "Onkyo", "author": "jorgh6", "description": "Onkyo AV Receiver", "name": "domoticz-onkyo-plugin", "source": "https://github.com/jorgh6/domoticz-onkyo-plugin/tree/master", "is_installed": false, "is_update_available": false}, "PioneerAVR": {"key": "PioneerAVR", "author": "febalci", "description": "Pioneer AVR", "name": "DomoticzPioneerAVR", "source": "https://github.com/febalci/DomoticzPioneerAVR/tree/master", "is_installed": false, "is_update_available": false}, "RAVEn": {"key": "RAVEn", "author": "dnpwwo", "description": "RAVEn Zigbee energy monitor", "name": "Domoticz-RAVEn-Plugin", "source": "https://github.com/dnpwwo/Domoticz-RAVEn-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "SNMPreader": {"key": "SNMPreader", "author": "ycahome", "description": "SNMP Reader", "name": "SNMPreader", "source": "https://github.com/ycahome/SNMPreader/tree/master", "is_installed": false, "is_update_available": false}, "SYSFS-Switches": {"key": "SYSFS-Switches", "author": "flatsiedatsie", "description": "SYSFS-Switches", "name": "GPIO-SYSFS-Switches", "source": "https://github.com/flatsiedatsie/GPIO-SYSFS-Switches/tree/master", "is_installed": false, "is_update_available": false}, "SeismicPortal": {"key": "SeismicPortal", "author": "febalci", "description": "Eartquake EMSC Data", "name": "DomoticzEarthquake", "source": "https://github.com/febalci/DomoticzEarthquake/tree/master", "is_installed": false, "is_update_available": false}, "Shelly_MQTT": {"key": "Shelly_MQTT", "author": "enesbcs", "description": "Shelly MQTT translator", "name": "Shelly MQTT", "source": "https://github.com/enesbcs/Shelly_MQTT/tree/master", "is_installed": true, "is_update_available": false}, "SmogTok": {"key": "SmogTok", "author": "smogtok", "description": "SmogTok Air Quality monitor", "name": "smogtokdomoticzplug", "source": "https://github.com/smogtok/smogtokdomoticzplug/tree/master", "is_installed": false, "is_update_available": false}, "Sonos": {"key": "Sonos", "author": "gerard33", "description": "Sonos Players", "name": "sonos", "source": "https://github.com/gerard33/sonos/tree/master", "is_installed": false, "is_update_available": false}, "Synology SurveillanceStation": {"key": "Synology SurveillanceStation", "author": "lolautruche", "description": "Synology SurveillanceStation", "name": "SurveillanceStationDomoticz", "source": "https://github.com/lolautruche/SurveillanceStationDomoticz/tree/master", "is_installed": false, "is_update_available": false}, "TasmotaH801": {"key": "TasmotaH801", "author": "stas-demydiuk", "description": "Control H801 LED WiFi Controller with Tasmota firmware via MQTT", "name": "H801 LED WiFi Controller with Tasmota firmware", "source": "https://github.com/stas-demydiuk/domoticz-h801-tasmota-plugin/tree/master", "is_installed": false, "is_update_available": false}, "Thermostat Weekly Scheduler": {"key": "Thermostat Weekly Scheduler", "author": "ArtBern", "description": "Manipulate schedule for virtual thermostat on weekly basis. Easy switch for timer plans.", "name": "Thermostat Weekly Scheduler", "source": "https://github.com/ArtBern/Scheduler/tree/master", "is_installed": false, "is_update_available": false}, "domoticz-theme-manager": {"key": "domoticz-theme-manager", "author": "galadril", "description": "Install and update themes via this theme manager", "name": "Domoticz Theme Manager ", "source": "https://github.com/galadril/domoticz-theme-manager/tree/master", "is_installed": false, "is_update_available": false}, "WAN-IP-CHECKER": {"key": "WAN-IP-CHECKER", "author": "ycahome", "description": "Wan IP Checker", "name": "WAN-IP-CHECKER", "source": "https://github.com/ycahome/WAN-IP-CHECKER/tree/master", "is_installed": false, "is_update_available": false}, "XiaomiPM": {"key": "XiaomiPM", "author": "febalci", "description": "Xiaomi PM2.5 Sensor", "name": "Xiaomi PM2.5 Sensor", "source": "https://github.com/febalci/DomoticzXiaomiPM2.5/tree/master", "is_installed": false, "is_update_available": false}, "YamahaPlug": {"key": "YamahaPlug", "author": "thomas-villagers", "description": "Yamaha AV Receiver with Kodi Remote", "name": "Yamaha AV Receiver", "source": "https://github.com/thomas-villagers/domoticz-yamaha/tree/master", "is_installed": false, "is_update_available": false}, "Zigate": {"key": "Zigate", "author": "zaraki673 & pipiche38", "description": "Allow Domoticz to access to the Zigate (Zigbee) worlds of devices", "name": "Zigate plugin", "source": "https://github.com/pipiche38/Domoticz-Zigate/tree/stable", "is_installed": false, "is_update_available": false}, "Zigbee2MQTT": {"key": "Zigbee2MQTT", "author": "stas-demydiuk", "description": "Domoticz integration with zigbee2mqtt project", "name": "Zigbee2MQTT", "source": "https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/tree/master", "is_installed": true, "is_update_available": false}, "deCONZ": {"key": "deCONZ", "author": "Smanar", "description": "deCONZ bridge (For Conbee,Raspbee)", "name": "Domoticz-deCONZ", "source": "https://github.com/Smanar/Domoticz-deCONZ/tree/master", "is_installed": false, "is_update_available": false}, "ebusd": {"key": "ebusd", "author": "guillaumezin", "description": "ebusd bridge", "name": "DomoticzEbusd", "source": "https://github.com/guillaumezin/DomoticzEbusd/tree/master", "is_installed": false, "is_update_available": false}, "ems-gateway": {"key": "ems-gateway", "author": "bbqkees", "description": "EMS bus Wi-Fi Gateway", "name": "ems-esp-domoticz-plugin", "source": "https://github.com/bbqkees/ems-esp-domoticz-plugin/tree/master", "is_installed": false, "is_update_available": false}, "eq3max": {"key": "eq3max", "author": "mvzut", "description": "eQ-3 MAX! Cube", "name": "maxcube-Domoticz-plugin", "source": "https://github.com/mvzut/maxcube-Domoticz-plugin/tree/master", "is_installed": false, "is_update_available": false}, "ewpe-smart-mqtt": {"key": "ewpe-smart-mqtt", "author": "stas-demydiuk", "description": "EwpeSmart (Gree, Cooper&Hunter, etc.) Air Conditioners control via MQTT", "name": "EwpeSmart Air Conditioners via MQTT", "source": "https://github.com/stas-demydiuk/domoticz-ewpe-smart-mqtt-plugin/tree/master", "is_installed": false, "is_update_available": false}, "freeboxv6": {"key": "freeboxv6", "author": "supermat", "description": "Freebox V6 (Revolution)", "name": "PluginDomoticzFreebox", "source": "https://github.com/supermat/PluginDomoticzFreebox/tree/master", "is_installed": false, "is_update_available": false}, "iDetect": {"key": "iDetect", "author": "d-EScape", "description": "iDetect Presence Detection", "name": "Domoticz_iDetect", "source": "https://github.com/d-EScape/Domoticz_iDetect/tree/master", "is_installed": false, "is_update_available": false}, "mikrotik-routeros": {"key": "mikrotik-routeros", "author": "mrin", "description": "Mikrotik RouterOS", "name": "domoticz-routeros-plugin", "source": "https://github.com/mrin/domoticz-routeros-plugin/tree/master", "is_installed": false, "is_update_available": false}, "owrtwifi2domo": {"key": "owrtwifi2domo", "author": "enesbcs", "description": "OpenWRT Wifi Presence Detector to MQTT translator", "name": "OpenWRT Wifi Presence MQTT", "source": "https://github.com/enesbcs/owrtwifi2domo/tree/master", "is_installed": false, "is_update_available": false}, "plugins-manager": {"key": "plugins-manager", "author": "stas-demydiuk", "description": "Allows to manage python plugins through custom UI page", "name": "Python Plugins Manager", "source": "https://github.com/stas-demydiuk/domoticz-plugins-manager/tree/master", "is_installed": true, "is_update_available": false}, "pyrtl433": {"key": "pyrtl433", "author": "enesbcs", "description": "RTL_433 MQTT receiver", "name": "RTL433 MQTT", "source": "https://github.com/enesbcs/pyrtl433/tree/master", "is_installed": false, "is_update_available": false}, "sony": {"key": "sony", "author": "gerard33", "description": "Sony Bravia TV (with Kodi remote)", "name": "sony-bravia", "source": "https://github.com/gerard33/sony-bravia/tree/master", "is_installed": false, "is_update_available": false}, "xfr-pimonitor": {"key": "xfr-pimonitor", "author": "Xorfor", "description": "PiMonitor", "name": "Domoticz-PiMonitor-Plugin", "source": "https://github.com/Xorfor/Domoticz-PiMonitor-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "xfr_aardbeving": {"key": "xfr_aardbeving", "author": "Xorfor", "description": "Dutch earthquakes", "name": "Domoticz-LastDutchEarthquake-Plugin", "source": "https://github.com/Xorfor/Domoticz-LastDutchEarthquake-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "xfr_discusage": {"key": "xfr_discusage", "author": "Xorfor", "description": "Disc usage", "name": "Domoticz-Disc-usage-Plugin", "source": "https://github.com/Xorfor/Domoticz-Disc-usage-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "xfr_openaq": {"key": "xfr_openaq", "author": "Xorfor", "description": "OpenAQ", "name": "Domoticz-OpenAQ-Plugin", "source": "https://github.com/Xorfor/Domoticz-OpenAQ-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "xfr_pihole": {"key": "xfr_pihole", "author": "Xorfor", "description": "Pi-hole summary", "name": "Domoticz-Pi-hole-Plugin", "source": "https://github.com/Xorfor/Domoticz-Pi-hole-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "xfr_speedtest": {"key": "xfr_speedtest", "author": "Xorfor", "description": "Speedtest", "name": "Domoticz-Speedtest-Plugin", "source": "https://github.com/Xorfor/Domoticz-Speedtest-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "WLANThermo": {"key": "WLANThermo", "author": "galadril", "description": "WLANThermo", "name": "WLANThermo", "source": "https://github.com/galadril/Domoticz-WLANThermo-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "WLED": {"key": "WLED", "author": "frustreermeneer", "description": "WLED", "name": "WLED Plugin", "source": "https://github.com/frustreermeneer/domoticz-wled-plugin/tree/master", "is_installed": false, "is_update_available": false}, "xiaomi-mi-robot-vacuum": {"key": "xiaomi-mi-robot-vacuum", "author": "mrin", "description": "Xiaomi Mi Robot Vacuum", "name": "Xiaomi Mi Robot Vacuum", "source": "https://github.com/mrin/domoticz-mirobot-plugin/tree/master", "is_installed": false, "is_update_available": false}, "yi-hack": {"key": "yi-hack", "author": "galadril", "description": "Yi Hack Plugin", "name": "Yi Hack Plugin", "source": "https://github.com/galadril/Domoticz-Yi-Hack-Plugin/tree/master", "is_installed": false, "is_update_available": false}, "Update_timer_Plugin": {"key": "Update_timer_Plugin", "author": "skarab22", "description": "Synchronize your devices on the corresponding active timer", "name": "Update_timer Plugin", "source": "https://github.com/skarab22/Domoticz-sync-timer/tree/master", "is_installed": false, "is_update_available": false}}}
`

**Comment by stas-demydiuk** [comment]
Yes, this device is required to support plugin's UI page
