### ISSUE TITLE
how to UNINSTALL this plugin ?

### ISSUE THREAD

**Issue by Eddie-BS** [stas-demydiuk/domoticz-plugins-manager#4]
Hi,
I tried this plugin and it looks ok but I don't need it anymore.
How do I uninstall it ?
removing the hardware removes the device.
removing the plugin from the plugin directory leaves me with the "custom/plugin-manager" entry 
even after refreshing and restarting domoticz ...

**Comment by stas-demydiuk** [comment]
Plugin should remove the custom page once you stop it. Anyway you can delete it from Domoticz custom pages manually by yourself at it should be enough. Tha path is `domoticz/www/tempaltes`
