### ISSUE TITLE
wrong directory for mqtt discovery plugin

### ISSUE THREAD

**Issue by reijerkerk-m** [stas-demydiuk/domoticz-plugins-manager#6]
In plugins.json directory  for mqtt discovery states MQTTDiscovery must be as name 
domoticz_mqtt_discovery (as in github)

![wrong mqtt discovery](https://user-images.githubusercontent.com/48696326/91606645-b6c30880-e972-11ea-9a2e-a77df94f8e20.jpg)

**Comment by stas-demydiuk** [comment]
I'm not sure I got your point. The current folder is the value in the `folder` key
